spring.application.name=producer-bus-location-emitter
server.port=8081

bus-info.number=1
bus-info.route.number=415
location.send.rate=5000
location.send.initial.delay=5000

### Message Broker
message.broker.topic=bus-location-queue
logging.level.org.springframework.kafka=DEBUG